import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google"

const quicksand = Quicksand({})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${quicksand.className} bg-[#eef4ff] font-light`}
    >
      <body>{children}</body>
    </html>
  );
}
